tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views
 

app_name = 'rango'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('about/', views.AboutView.as_view(), name='about'),
	path('category/<slug:category_name_slug>/',
		views.ShowCategoryView.as_view(), name='show_category'),
	path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
	path('<slug:category_name_slug>/add_page/', 
		views.AddPageView.as_view(), name='add_page'),
	path('cookie_page/', views.cookie_page, name='cookie_page'),
	path('session_page/', views.session_page, name='session_page'),
	path('goto/', views.GoToView.as_view(), name='goto'),
	path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
	path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
	path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
	path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
	path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
	path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
	path('guess_number_game/', views.GuessNumberView.as_view(), name='guess_number_game'),
	path('random_tiles/', views.RandomTiles.as_view(), name='random_tiles'),
	path('bouncing_balls/', views.BouncingBallsView.as_view(), name='bouncing_balls'),
	path('comments/', views.CommentsView.as_view(), name='comments'),
	path('privacy/', views.PrivacyView.as_view(), name='privacy'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, reverse
from django.conf.urls.static import static
from django.conf import settings

from rango import views 
from registration.backends.simple.views import RegistrationView 

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('oauth_accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.template.defaultfilters import slugify 

class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		self.views = self.views if self.views >= 0 else 0
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.name 

class Page(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title 

class Comment(models.Model):
	author = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)

	# Only one way relationship with Category (many to one)
	# Many comments can be assigned to one Category
	category = models.ForeignKey('Category', null=True, on_delete=models.CASCADE)


class UserProfile(models.Model):
	# This line is required. Links UserProfile to a User model instance.
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	# The additional attributes we wish to include
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __str__(self):
		return self.user.username 

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User 
from rango.models import Page, Category, UserProfile 


class CategoryForm(forms.ModelForm):
	# by listing the fields in the form class, we are overriding
	# the behaviour from the model, enabling to extend it
	name = forms.CharField(max_length=128,
		help_text="Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	# An inline class to provide additional information on the form.
	class Meta:
		# Provide an association between the ModelForm and a model
		# defines which fields will be included in the form
		model = Category
		fields = ('name', )

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=128,
		help_text="Please enter the title of the page.")
	url = forms.URLField(max_length=200,
		help_text="Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	class Meta:
		# Provide an association between the ModelForm and a model
		model = Page 

		# What fields do we want to include in our form?
		# This way we don't need every field in the model present.
		# Some fieLds may allow NULL values, so we may not want to include them.
		# Here, we are hiding the foreign key.
		# we can either exclude category field from the form,
		exclude = ('category',)
		# or specify the fields to include (i.e. not include the category field)
		#fields = ('title', 'url', 'views')

		def clean(self):
			cleaned_data = self.cleaned_data
			url = cleaned_data.get('url')
			print(f'URL: {url}')
			# If url is not empty and doesn't start with 'http://',
			# then prepend 'http://'.
			if url and not url.startswith('http://'):
				url = 'http://' + url 
				cleaned_data['url'] = url 

			print(f"URL NOW: {cleaned_data['url']}")
			return cleaned_data 

class UserForm(forms.ModelForm):
	# overriding the password field to extend it with passwordinput widget
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User 
		# define which fields will be included in the form
		fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile 
		fields = ('website', 'picture')


class CommentForm(forms.Form):
	body = forms.CharField(widget=forms.Textarea(
		attrs={
			'class': 'form-control',
			'placeholder': 'Leave a comment!'
		})
	)

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.urls import reverse 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 

from datetime import datetime 
from rango.models import Category, Page, Comment, UserProfile
from rango.forms import CategoryForm, PageForm, CommentForm
from rango.forms import UserForm, UserProfileForm 
from rango.bing_search import run_query
from django.views import View 
from django.utils.decorators import method_decorator

class PrivacyView(View):
	def get(self, request):
		return render(request, 'rango/privacy.html')

class BouncingBallsView(View):
	def get(self, request):
		return render(request, 'rango/bouncing_balls.html')

class GuessNumberView(View):
	def get(self, request):
		return render(request, 'rango/guess_number_game.html')

class RandomTiles(View):
	def get(self, request):
		return render(request, 'rango/random_tiles.html')

class SearchAddPageView(View):
	'''
	AJAX view with get method that adss a Page model object into the Category model object. 
	Returns html with just the Page listing.
	'''
	@method_decorator(login_required)
	def get(self, request):
		category_id = request.GET['category_id']
		page_title = request.GET['page_id']
		page_url = request.GET['page_url']

		# Check whether category exitst
		try:
			category = Category.objects.get(id=int(category_id))
		except Category.DoesNotExist:
			return HttpResponse('Error - category not found.')
		except ValueError:
			return HttpResponse('Error - bad category ID.')

		# Add the page to category if it does not exist yet
		page = Page.objects.get_or_create(category=category, title=page_title, url=page_url)
			
		pages = Page.objects.filter(category=category).order_by('-views')	
		return render(request, 'rango/page_listing.html', {'pages':pages})



def get_category_list(max_results=0, starts_with=''):
	'''
	Help function for the Category "Sugestion" functionality. Returns list of Category model objects.
	'''
	category_list = []

	if starts_with:
		category_list = Category.objects.filter(name__istartswith=starts_with)

	if max_results > 0:
		if len(category_list) > max_results:
			category_list = category_list[:max_results]

	return category_list 


class CategorySuggestionView(View):
	'''
	AJAX view with get method to process the search input from the user
	and return the list of Categories that are matching the search.
	'''
	def get(self, request):
		suggestion = request.GET['suggestion']
		category_list = get_category_list(max_results=8, starts_with=suggestion)

		if len(category_list) == 0:
			category_list = Category.objects.order_by('-likes')

		return render(request, 'rango/categories.html', {'categories': category_list})

class LikeCategoryView(View):
	'''
	AJAX view with get method to process the "like" Category button. Get method
	receives the category id, increases the num of likes which also returns.
	'''
	@method_decorator(login_required)
	def get(self, request):
		category_id = request.GET['category_id']

		try:
			category = Category.objects.get(id=int(category_id))
		except Category.DoesNotExist:
			return HttpResponse(-1)
		except ValueError:
			return HttpResponse(-1)

		category.likes = category.likes + 1
		category.save()

		return HttpResponse(category.likes)

class ListProfilesView(View):
	'''
	Returns response with list of all users.
	'''
	@method_decorator(login_required)
	def get(self, request):
		profiles = UserProfile.objects.all()

		return render(request, 'rango/list_profiles.html', {'userprofile_list': profiles})

class ProfileView(View):
	'''
	Form processing view with both Get and Post methods to display the requested
	user information or to update it.
	'''
	def get_user_details(self, username):
		'''
		Helper method, returns the passed user and userprofile module objects
		given in the parameter as username.
		'''
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			# this will raise TypeError in the calling method
			return None

		userprofile = UserProfile.objects.get_or_create(user=user)[0]

		# Create a form object and fill it with the users information
		form = UserProfileForm({'website': userprofile.website,
								'picture': userprofile.picture})
		return (user, userprofile, form)

	@method_decorator(login_required)
	def get(self, request, username):
		''' 
		Get method returns response with the requested user, userprofile and form object.
		'''
		try:
			(user, userprofile, form) = self.get_user_details(username)
		except TypeError:
			return redirect('rango:index')

		context_dict = {'userprofile': userprofile,
						'selecteduser': user,
						'form': form}
		return render(request, 'rango/profile.html', context_dict)

	@method_decorator(login_required)
	def post(self, request, username):
		'''
		Post method receives user form data posted by the user. 
		The data are filled in a user profile form, validated and then saved.
		Method redirects the user to the index page.
		'''
		try:
			(user, userprofile, form) = self.get_user_details(username)
		except TypeError:
			return redirect('rango:index')
		
		# Users can change only their own profiles
		if request.user != user:
			return redirect('rango:index')

		form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

		if form.is_valid():
			form.save(commit=True)
			return redirect('rango:profile', user.username)
		else:
			print(form.errors)

		# The posted data are invalid, return them in the form
		context_dict = {'userprofile': userprofile,
						'selecteduser': user,
						'form': form}
		return render(request, 'rango/profile.html', context_dict)
'''
def about(request):
	context_dict = {'your_name' :'Adam Janca'}
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	return render(request, 'rango/about.html', context=context_dict)
'''

class AboutView(View):
	def get(self, request):
		context_dict = {}
		context_dict['visits'] = request.session['visits']
		return render(request, 'rango/about.html', context_dict)

'''
@login_required
def register_profile(request):
	form = UserProfileForm()

	if request.method == 'POST':
		form = UserProfileForm(request.POST, request.FILES)

		if form.is_valid():
			user_profile = form.save(commit=False)
			user_profile.user = request.user 
			user_profile.save()

			return redirect('rango:index')
		else:
			print(form.errors)
	context_dict = {'form': form}
	return render(request, 'rango/profile_registration.html', context_dict)
'''

class RegisterProfileView(View):
	'''
	Step 2 registration.
	'''
	@method_decorator(login_required)
	def post(self, request):
		form = UserProfileForm(request.POST, request.FILES)
		if form.is_valid():
			user_profile = form.save(commit=False)
			user_profile.user = request.user
			user_profile.save()
			return redirect('rango:index')
		else:
			print(form.errors)
			context_dict = {'form': form}
			return render(request, 'rango/profile_registration.html', context_dict)

	@method_decorator(login_required)
	def get(self, request):
		form = UserProfileForm()
		context_dict = {'form': form}
		return render(request, 'rango/profile_registration.html', context_dict)

'''
def goto_url(request):
	page_id = None
	if request.method == 'GET':
		page_id = request.GET.get('page_id')
		if not page_id:
			return redirect(reverse('rango:index'))

		try:
			page = Page.objects.get(id=page_id)
		except Page.DoesNotExist:
			return redirect(reverse('rango:index'))

		page.views += 1
		page.save()
		return redirect(page.url)
	
	return redirect(reverse('rango:index'))
'''

class GoToView(View):
	'''
	Every page in the category when clicked sends Get request to this view
	with the page id's as a parameter. The view increments the views attribute
	of the page's model object.
	'''
	def get(self, request):
		page_id = request.GET.get('page_id')
		if not page_id:
			return redirect(reverse('rango:index'))

		try:
			page = Page.objects.get(id=page_id)
		except Page.DoesNotExist:
			return redirect(reverse('rango:index'))

		page.views += 1
		page.save()
		return redirect(page.url)
	
	def post(self, request):
		return redirect(reverse('rango:index'))	

'''
def search(request):
	result_list = []
	query = ''
	if request.method == 'POST':
		query = request.POST['query'].strip()
		if query:
			# Run our Bing function to get the results list!
			result_list = run_query(query)

	return render(request, 'rango/search.html', {'result_list': result_list, 'query_string':query})
'''

def session_page(request):
	context_dict = {}

	if request.method == 'POST':
		name = request.POST['username_form']
		request.session['username_session'] = name 
		
		return redirect(reverse('rango:session_page'))


	# GET Method
	username_session = request.session.get('username_session')
	context_dict['username_session'] = username_session
	return render(request, 'rango/session_page.html', context_dict)

def cookie_page(request):
	''' 
	Has a page counter cookie and a form to obtain name from user
	via a cookie and to display it
	''' 
	context_dict = {}

	page_counter = int(request.COOKIES.get('cookie_page_counter', 1))
	context_dict['cookie_page_counter'] = page_counter 

	if request.method == 'POST':
		username_form = request.POST.get('username_form')
		username_form = username_form if username_form else 'default name'

		# Update context dict so you can display the information 
		context_dict['username_cookie'] = username_form
		
		# Create response object
		response = render(request, 'rango/cookie_page.html', context_dict)

		# Update the response object with the new cookie and send it back to the client
		response.set_cookie('username_cookie', username_form)
		return response

	# GET METHOD 
	username_cookie = request.COOKIES.get('username_cookie', 'no name')
	context_dict['username_cookie'] = username_cookie

	# Create response object

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Category
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Category</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">		
			<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}<br />
					{{ field }}<br />
					<div class="p-2"></div>
				{% endfor %}
				<button class="btn btn-primary" type="submit" name="submit">Create Category</button>
				<div class="p-5"></div>
			</form>
		</div>
		</div>
	</div>
	
	
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{% if category %}
		{{ category }} - 
	{% endif %}
		Add Page
{% endblock %}

{% block body_block %}
	{% if category %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add Page to {{ category.name }}</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}<br />
					{{ field }}<br />
					<div class="p-2"></div>
				{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">
					Add Page
				</button>
				<div class="p-5"></div>
			</form>
		</div>
	</div>
	{% else %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Page</h1>
		</div>
	</div>
	<div>
		The specified category does not exist.
	</div>
	{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head_block %}
    {% endblock %}
    <title>
        Jarek - {% block title_block %}{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">
                        <i class="fa fa-home"></i>&nbsp;Home</a></li>

                    <!-- Categories button is displayed only on extra small devices, and have a js code on click -->
                    <!-- TODO - replace with ev hnadler -->
                    <li class="nav-item d-block d-md-none"><a class="nav-link" onclick="toggleBar()" href="#">
                        <i class="fa fa-list"></i>&nbsp;Categories</a></li>
                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">
                            <i class="fa fa-plus-square"></i>&nbsp;Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">
                            <i class="fa fa-address-book"></i>&nbsp;List Profiles</a></li>
                        {% endif %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-gamepad"></i>&nbsp;Games<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'rango:guess_number_game' %}">Guess A Number</a></li>
                                <li><a href="{% url 'rango:random_tiles' %}">Random Tiles</a></li>
                                <li><a href="{% url 'rango:bouncing_balls' %}">Bouncing Balls</a></li>
                            </ul>
                        </li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'rango:comments' %}">
                            <i class="fa fa-comments"></i>&nbsp;Comments</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:about' %}">
                            <i class="fa fa-question-circle"></i>&nbsp;About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:privacy' %}">
                            <i class="fa fa-list"></i>&nbsp;Privacy</a></li>
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">
                            <i class="fa fa-user"></i>&nbsp;Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                            <i class="fa fa-sign-out"></i>&nbsp;Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">
                            <i class="fa fa-sign-in"></i>&nbsp;Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="mySidebar" class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="w-75 ml-3">
                        <input type="search" id="search-input" class="form-control ds-input"
                            placeholder="Search..." />
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                    
                        {% get_category_list category %}
                    
                    </div>
                </nav>
                
                <main id="main_content" role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">      
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
        <script src="{% static 'js/subnav.js' %}"></script>
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
	{% for c in categories %}
		{% if c == current_category %}
			<li class="nav-item">
				<a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>&nbsp;{{ c.name }}
				</a>
			</li>
		{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>&nbsp;{{ c.name }}
				</a>
			</li>
		{% endif %}
	{% endfor %}
{% else %}
	<li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/cookie_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Test cookies
{% endblock %}

{% block body_block %}
<p>Display the cookies here: {{ cookie_page_counter }}</p>
<p>Your cookie username is: {{ username_cookie }}</p>
	<form id="cookie_form" method="post" action="{% url 'rango:cookie_page' %}">
		{% csrf_token %}
		Username: <input type="text" name="username_form" value="" size="50" />
		<br />
		<input type="submit" value="submit" />
	</form>

{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Home
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Adam's Web Catalog</h1>
			<div>
				<strong>
					{% if user.is_authenticated %}
						Hello {{ user.username }}! Welcome back!
					{% else %}
						Hey there! Please <a href="{% url 'registration_register' %}">register</a> and <a href="{% url 'auth_login' %}">log in</a>
					{% endif %}
				</strong>
				<strong style="display:none">{{ boldmessage }}</strong>
			</div>
		</div>
	</div>

	
	<p style="display:none">Number of visits {{ visits }}</p>
	<div class="container">
		<p>Browse around the categories and find out about some of the interesting web pages added by other users. Registered users are free to add their favourite pages to the categories and also to create new categories.</p>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="card mb-6">
					<div  class="card-body">
						<h2>Most Liked Categories</h2>
						<p class="card-text">
							{% if categories %}
							<ul class="list-group">
								{% for category in categories %}
								<li class="list-group-item">
									<a href="{% url 'rango:show_category' category.slug %}">
									{{ category.name }}</a>
								</li>
								{% endfor %}
							</ul>
							{% else %}
							<strong>There are no categories present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card mb-6">
					<div class="card-body">
						<h2>Most Viewed Pages</h2>
						<p class="card-text">
							{% if pages %}
							<ul class="list-group">
								{% for page in pages %}
								<li class="list-group-item">
									<a href="{{ page.url }}">{{ page.title }}</a>
								</li>
								{% endfor %}
							</ul>
							{% else %}
							<strong>There are no pages present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

tango_with_django_project/templates/rango/page_listing.html
{% if pages %}
	<ul>
	{% for page in pages %}
		<li><a href="{% url 'rango:goto' %}?page_id={{ page.id}}">{{ page.title }}</a> {{ page.views }} view{{ page.views | pluralize}}</li>
	{% endfor %}
	</ul>
{% else %}
	<strong>No pages currently in category.</strong>
{% endif %}